import {GoogleGenAI} from "@google/genai"
import {z} from "zod"
import {zodToJsonSchema} from "zod-to-json-schema"
import puppeteer from "puppeteer"

const  ai = new GoogleGenAI({apiKey:process.env.GOOGLE_GENAI_API_KEY})


const resumePDFschema = z.object({
  html: z.string().describe(
    "Complete HTML document for a professional resume, including inline CSS styling, proper structure with headings, sections like education, skills, experience, and formatted for A4 PDF"
  ),
});


async function convertPDF(resumeHtml) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(resumeHtml , {waitUntil:"networkidle0"});
    const pdfBuffer = await page.pdf({format:"A4", printBackground:true, margin:{top:"20mm", bottom:"20mm", left:"15mm", right:"15mm"}});
    await browser.close();
    return pdfBuffer;
    
}




async function generateResumeAi({jobDescription,resume,selfDescription}) {
    // const trimmedResume = resume?.slice(0, 2000);

      const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `



    const response = await ai.models.generateContent({
        model:"gemini-2.5-flash",
        contents:prompt,
        config:{
            responseMimeType:"application/json",
            responseSchema: zodToJsonSchema(resumePDFschema)
        }
    })
    
//    let resumContent =  JSON.parse(response.text)
//     const pdfBuffer = await convertPDF(resumContent.html)
//     return pdfBuffer;

 let parsed;

  try {
    parsed = JSON.parse(response.text);
  } catch (err) {
    console.error("Invalid JSON from AI:", response.text);
    throw new Error("AI returned invalid JSON");
  }

  if (!parsed.html || parsed.html.length < 100) {
    throw new Error("Invalid resume HTML generated");
  }

  const pdfBuffer = await convertPDF(parsed.html);
  return pdfBuffer;

}

export default generateResumeAi